environment: production
title: Matter
email: hello@madebymatter.co
description: The digital design portfolio of Belgium-based designer, Jeremy Swinnen
baseurl: ''
url: 'https://madebymatter.co'
twitter_username: jereswinnen
github_username: jereswinnen
dribbble_username: jereswinnen

markdown: kramdown
theme:

plugins:
  - jekyll-feed

include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - config.codekit3

collections:
  projects:
    output: true
    permalink: /work/:title/
